USE master;
GO

CREATE DATABASE WebSharp;
GO
USE WebSharp;
GO

CREATE TABLE dbo.Countries(
	Id INT PRIMARY KEY IDENTITY,
	CountryName VARCHAR(255) NOT NULL,
	-- Continent foreign ....
)
GO

CREATE TABLE dbo.States(
	Id INT PRIMARY KEY IDENTITY,
	StateName VARCHAR(255) NOT NULL,
	IdCountry INT FOREIGN KEY REFERENCES dbo.Countries(Id)
);
GO

CREATE TABLE dbo.Cities(
	Id INT PRIMARY KEY IDENTITY,
	CityName VARCHAR(255) NOT NULL,
	IdState INT FOREIGN KEY REFERENCES dbo.States(Id)
);
GO


CREATE TABLE dbo.News(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(255) NOT NULL,
	Thumbnail VARCHAR(MAX) NOT NULL,
	Content VARCHAR(MAX) NOT NULL,
	IdCity INT FOREIGN KEY REFERENCES dbo.Cities(Id),
	NewsDate DATETIME DEFAULT(GETDATE())
	-- Topics
);
GO


CREATE TABLE dbo.Topics(
	Id INT PRIMARY KEY IDENTITY,
	TopicName VARCHAR(80) NOT NULL,
	Quantity INT
);
GO

CREATE TABLE dbo.TopicsXNews(
	Id INT PRIMARY KEY IDENTITY,
	IdTopic INT FOREIGN KEY REFERENCES dbo.Topics(Id),
	IdNews INT FOREIGN KEY REFERENCES dbo.News(Id)
)